version: "3.1"

services:
  was:
    image: ${WAS_IMAGE_NAME}:${WAS_IMAGE_VERSION}
    container_name: was
    restart: always
    ports:
      - 8080:8080
    networks:
      - chirp-bridge

  webServer:
    image: ${WEB_SERVER_IMAGE_NAME}:${WEB_SERVER_VERSION}
    container_name: web_server
    restart: always
    ports:
      - 80:80
    networks:
      - chirp-bridge

  mysql:
    image: ${MYSQL_DB_NAME}:${MYSQL_DB_IMAGE_VERSION}
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - chirp-bridge
    volumes:
      - ${DIR_MOUNTED_MYSQL}:/var/lib/mysql

  redis:
    image: ${REDIS_DB_IMAGE_NAME}:${REDIS_DB_IMAGE_VERSION}
    container_name: redis_db
    restart: always
    ports:
      - 6379:6379
    networks:
      - chirp-bridge

networks:
  chirp-bridge:
    driver: bridge